### ISSUE TITLE
长文档动态加载时标题编号可能会有问题

### ISSUE THREAD

**Issue by leolee9086** [dale0525/siyuan-auto-seq-number#3]
因为目前的编号是直接从protyle中的DOM元素获取计数,在触发动态加载时(以及类似反链\聚焦等局部加载的情况),由于上下文DOM不完整,标题编号可能与实际文档结构不一致,使用getDOC接口获取文档的完整DOM计算标题编号可能可以解决

**Comment by dale0525** [comment]
Fixed.
